# Generated by Django 4.2.6 on 2023-10-23 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_joined_dat_member_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='joined_dat',
            new_name='joined_date',
        ),
    ]
