# Generated by Django 4.2.6 on 2023-10-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_rename_joined_dat_member_joined_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='LinkedIn_usr_name',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='Twitter_usr_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='subscriped_usr',
            field=models.BooleanField(null=True),
        ),
    ]
