# Generated by Django 4.2.6 on 2023-10-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_member_linkedin_usr_name_member_twitter_usr_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='LinkedIn_usr_name',
            field=models.URLField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
